# Generated by Django 3.0.2 on 2020-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200322_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
