# Generated by Django 3.0.2 on 2020-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_message_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='gmt_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
